---
bibliography: qm_bibliography.bib
csl: harvard-cite-them-right.csl
title: CASA0007 Written Investigation
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
    mainfont: Spectral
    sansfont: Calibri
    monofont: Courier New
    papersize: a4
    geometry:
      - top=25mm
      - left=40mm
      - right=30mm
      - bottom=25mm
      - heightrounded
    toc: false
    number-sections: true
    colorlinks: true
    highlight-style: github
---

## Preface

### The Task

Define a research question of your choice in a topic that is related to cities research and investigate this question, using the quantitative methods from this module as a basis. Present your investigation and its conclusions as a written report. You need to use Python as the main language in this investigation, rather than other programming languages or tools (e.g. R, Excel).

### Audience

Your work should be clear and comprehensible for an audience with a sound foundation of quantitative understanding. You should assume a detailed knowledge of the methods covered in the course. Briefly explain the purpose of each method that you employ.

\

**Length**: The maximum length of the text is 1750 words, excluding graphs, tables, other figures and code extracts. Footnotes are included in the word limit. In addition, the work as a whole must not exceed 7 pages, with a minimum font size of 12. The word count must be stated at the end of the text. The only exception to the above is the bibliography, which should appear on its own page at the end of the document, and which is not counted in the word limit.

\


## Introduction and Background (400 words)

*Description*: This should be a brief discussion of sources relevant to your work. Be sure to consider sources relating to both the context of the research question you have chosen and the methods that other authors have used to address similar questions. Ensure that you take a critical perspective on the sources you reference and end by summarising the relevance of what you have learnt for your own investigation.  

Proposed Structure:  

-   Introduce; overview of HIV rates in the UK, at-risk populations, trends in diagnosis. Describe PrEP as a medication and how it is used. Describe PrEP funding and provision in the UK (NHS via SHSs). 

-   Discuss the research in PrEP access, and spatial disparities. Introduce and report the findings of key studies (mostly from US and Australia). Refer to PHE statistics on disparities in HIV care between metropolitan and regional SHSs. 

-   Discuss gaps in the research; lots of work on qualitative understanding of differences between urban-rural accessibility, however lack of broader quantitative studies. Therefore this project will provide a quantitative basis across the whole UK to support or contrast with qualitative research.

*From research proposal* PrEP was made available as a publicly subsidised medication in England through the NHS in 2020. Given that regional variation in access was identified as an independent factor in PrEP uptake in Australia, and both countries have only recently made the subsidised medication available nationwide, there is reason to believe that a similar pattern may be evident in the UK. This has implications for health equity and identifying areas of greatest need for PrEP access and education.

HIV Pre-Exposure Prophylaxis (PrEP) ...  


## Research Question (100 words)

**Research Question**: How are levels of unmet HIV pre-exposure prophylaxis (PrEP) need associated with urban-rural divides in England?

**Objectives**:

1.  To assess whether PrEP use and need differs across urban and rural areas. *Chi-squared/T-test*

    i.  *Hypothesis:* PrEP use in urban areas is higher than regional/rural


2.  To identify the characteristics across urban and rural regions which best explain the distribution of unmet PrEP need. *Regression analysis*

3.  To assess whether areas with more established communities of sexual minorities have lower rates of PrEP unmet need, across the total resident population. *How to test this?*

    i.  *Hypothesis:* Areas with higher proportion of LGB+ population will have greater sexual health literacy, and healthcare workers will have greater expertise in HIV and sexual health care, which will improve PrEP uptake across the community *as a whole*.
    ii. *Hypothesis:* xxx
  
  
**Notes from Lecture, Week 6**: Follow the hypothesis testing process and present this *clearly* and *explicitly* in text. E.g.  

1.    State the null + alternative hypothesis

2.    State the data type of variables

3.    State the test statistic used (e.g. chi-squared)

4.    State the test results

5.    State hypothesis conclusion (evidence for null or alternative?)


## Data Sources (150 words)

*Description*: Communicate the key features of your data to the reader through summary statistics and appropriate figures and tables.

Text

## Methodology (150 words)

*Description*: Your methodology must demonstrate an understanding of quantitative techniques and their value. Consider which of the methods from the course would be most appropriate to deploy in the investigation of your particular question.

Text

## Results (300 words)

*Description*: Consider the way in which you present your results carefully. The goal should be clarity of communication. In some circumstances, a table of values may be perfectly adequate. In other circumstances, a graph or diagram may be more appropriate.

Text

## Discussion (500 words)

*Description*: When discussing your results, you should demonstrate your understanding of the quantitative methods that you have employed and your ability to clearly interpret any output that you have observed. Avoid summarising information that has already been clearly presented by means of a table or graph and concentrate on highlighting key facts and interpreting outcomes in terms of your research objectives.

Text

## Conclusion (150 words)

*Description*: Your conclusion must relate back to your research question (even if your results are inconclusive) and must be based on all of the information that you have gained and the interpretations that you have outlined in the previous sections.

Text

{{< pagebreak >}}

## References
